name: Release

on:
  push:
    tags:
      - 'v[1-9]+[0-9]?.[0-9]+.[0-9]+'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2

      - id: tag
        run: |
          : Generate Short Tags
          tag="${{ github.ref }}"
          tag="${tag#refs/tags/}"
          git tag -f "${tag%.*}"
          latest="$(git tag -l --sort v:refname v[0-9]* | sed -E -n 's/^v([[:digit:]]+\.[[:digit:]]+)\..*/\1/p' | tail -n 1)"
          test "${tag%.*}" != "${latest}" || git tag -f "${tag%%.*}"
          git push --tags --force
